"""
Character Prompt Builder Nodes
original inspiration for this was forked from comfyui-easy-use by AI Wiz Art (Stefano Flore)
"""

from .node_defs.female_person import NODE_CLASS_MAPPINGS as FEMALE_PERSON_CLASS_MAPPINGS
from .node_defs.female_person import (
    NODE_DISPLAY_NAME_MAPPINGS as FEMALE_PERSON_DISPLAY_NAME_MAPPINGS,
)
from .node_defs.male_person import NODE_CLASS_MAPPINGS as MALE_PERSON_CLASS_MAPPINGS
from .node_defs.male_person import (
    NODE_DISPLAY_NAME_MAPPINGS as MALE_PERSON_DISPLAY_NAME_MAPPINGS,
)
from .node_defs.female_fashion import NODE_CLASS_MAPPINGS as FASHION_CLASS_MAPPINGS
from .node_defs.female_fashion import (
    NODE_DISPLAY_NAME_MAPPINGS as FASHION_DISPLAY_NAME_MAPPINGS,
)
from .node_defs.male_fashion import NODE_CLASS_MAPPINGS as MALE_FASHION_CLASS_MAPPINGS
from .node_defs.male_fashion import (
    NODE_DISPLAY_NAME_MAPPINGS as MALE_FASHION_DISPLAY_NAME_MAPPINGS,
)
from .node_defs.female_poses import NODE_CLASS_MAPPINGS as FEMALE_POSES_CLASS_MAPPINGS
from .node_defs.female_poses import (
    NODE_DISPLAY_NAME_MAPPINGS as FEMALE_POSES_DISPLAY_NAME_MAPPINGS,
)
from .node_defs.male_poses import NODE_CLASS_MAPPINGS as MALE_POSES_CLASS_MAPPINGS
from .node_defs.male_poses import (
    NODE_DISPLAY_NAME_MAPPINGS as MALE_POSES_DISPLAY_NAME_MAPPINGS,
)
from .render_prompt import NODE_CLASS_MAPPINGS as SHOW_TEXT_CLASS_MAPPINGS
from .render_prompt import NODE_DISPLAY_NAME_MAPPINGS as SHOW_TEXT_DISPLAY_NAME_MAPPINGS
from .node_defs.scene import NODE_CLASS_MAPPINGS as SCENE_CLASS_MAPPINGS
from .node_defs.scene import NODE_DISPLAY_NAME_MAPPINGS as SCENE_DISPLAY_NAME_MAPPINGS

NODE_CLASS_MAPPINGS = {
    **FEMALE_PERSON_CLASS_MAPPINGS,
    **MALE_PERSON_CLASS_MAPPINGS,
    **FASHION_CLASS_MAPPINGS,
    **MALE_FASHION_CLASS_MAPPINGS,
    **FEMALE_POSES_CLASS_MAPPINGS,
    **MALE_POSES_CLASS_MAPPINGS,
    **SHOW_TEXT_CLASS_MAPPINGS,
    **SCENE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **FEMALE_PERSON_DISPLAY_NAME_MAPPINGS,
    **MALE_PERSON_DISPLAY_NAME_MAPPINGS,
    **FASHION_DISPLAY_NAME_MAPPINGS,
    **MALE_FASHION_DISPLAY_NAME_MAPPINGS,
    **FEMALE_POSES_DISPLAY_NAME_MAPPINGS,
    **MALE_POSES_DISPLAY_NAME_MAPPINGS,
    **SHOW_TEXT_DISPLAY_NAME_MAPPINGS,
    **SCENE_DISPLAY_NAME_MAPPINGS,
}
